name: Deploy website on push

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            **/.git*
            **/.github/**
            **/.vscode/**
            **/.idea/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
            **/.env.*
            !**/.env.example
            **/.DS_Store
            **/.ftp-deploy-sync-state.json
            **/.ftpquota
